apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pizze.v1alpha1.memenetes
spec:
  group: v1alpha1.memenetes
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tomato:
                  type: bool
                salami:
                  type: string
                mozarella:
                  type: string
                size:
                  type: string
  scope: Namespaced
  names:
    plural: pizze
    singular: pizza
    kind: Pizza
    shortNames:
    - piz